name: CI Testing

on:
  push:
    branches: [ main, develop ]
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-*'
  pull_request:
    branches: [ main, develop ]

jobs:
  run_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ['3.9', '3.10']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install cryoDRGN with pytest dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest-xdist
          python3 -m pip install .

      - name: Pytest
        run: |
	  pytest -v -n0 -k $testStr1 --dist loadscope
	  pytest -v -n2 -k $testStr2 --dist loadscope
        env:
	  testStr1: 'not test_integration and not test_pipeline and not test_reconstruct'
	  testStr2: 'test_integration or test_pipeline or test_reconstruct'
